version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
        NEXT_PUBLIC_GOOGLE_MAPS_BASE_URL: ${NEXT_PUBLIC_GOOGLE_MAPS_BASE_URL}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    image: "europe-north1-docker.pkg.dev/${PROJECT_ID}/app/outlet-frontend:latest"
  
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
    image: "europe-north1-docker.pkg.dev/${PROJECT_ID}/app/outlet-admin:latest"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "europe-north1-docker.pkg.dev/${PROJECT_ID}/app/outlet-api:latest"