name: Deploy to Google Cloud

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
      - 'docker-compose.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Fetch .env from Secret Manager
        run: |
          gcloud secrets versions access latest --secret="frontend-env" > frontend/.env.production

      - name: Build and push Docker image with docker-compose
        run: |
          docker-compose build frontend
          docker-compose push frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy outlet-frontend \
            --image europe-north1-docker.pkg.dev/$PROJECT_ID/app/outlet-frontend:latest \
            --allow-unauthenticated \
            --platform managed \
            --region europe-north1